name: scan_vision_app
description: ScanVisionApp

version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_ml_vision: ^0.9.3+5
  image_cropper: ^1.2.1
  image_picker: ^0.6.3+1
  flutter_tts: ^0.8.7
  flutter_speed_dial: ^1.2.5
  esys_flutter_share: ^1.0.2
  cloud_firestore: ^0.13.1+1
  cached_network_image: ^2.0.0
  firebase_storage: ^3.1.1
  path: ^1.6.4
  flutter_staggered_grid_view: ^0.3.0
  flutter_cache_manager: ^1.1.3
  zoom_widget: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
